<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AcceptCoockiesPopup</name>
   <tag></tag>
   <elementGuidId>f4b51dad-48d0-417a-b8a0-e3a00888f123</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CXQnmb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>id(&quot;CXQnmb&quot;)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4c391b5a-e88e-46e3-ad17-0c85d2dbb4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>KxvlWc</value>
      <webElementGuid>21aab00e-581d-4fad-b451-46a7a6e187f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CXQnmb</value>
      <webElementGuid>a093919c-08df-43d6-b7a6-6d070ad8dccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ru‪Русский‬‪Afrikaans‬‪azərbaycan‬‪bosanski‬‪català‬‪Čeština‬‪Cymraeg‬‪Dansk‬‪Deutsch‬‪eesti‬‪English (United Kingdom)‬‪English (United States)‬‪English‬‪Español (España)‬‪Español (Latinoamérica)‬‪euskara‬‪Filipino‬‪Français (Canada)‬‪Français (France)‬‪Gaeilge‬‪galego‬‪Hrvatski‬‪Indonesia‬‪isiZulu‬‪íslenska‬‪Italiano‬‪Kiswahili‬‪latviešu‬‪lietuvių‬‪magyar‬‪Melayu‬‪Nederlands‬‪norsk‬‪o‘zbek‬‪polski‬‪Português (Brasil)‬‪Português (Portugal)‬‪română‬‪shqip‬‪Slovenčina‬‪slovenščina‬‪srpski (latinica)‬‪Suomi‬‪Svenska‬‪Tiếng Việt‬‪Türkçe‬‪Ελληνικά‬‪беларуская‬‪български‬‪кыргызча‬‪македонски‬‪монгол‬‪српски (ћирилица)‬‪Українська‬‪ქართული‬‪қазақ тілі‬‪հայերեն‬‫עברית‬‫اردو‬‫العربية‬‫فارسی‬‪አማርኛ‬‪नेपाली‬‪मराठी‬‪हिन्दी‬‪বাংলা‬‪ਪੰਜਾਬੀ‬‪ગુજરાતી‬‪தமிழ்‬‪తెలుగు‬‪ಕನ್ನಡ‬‪മലയാളം‬‪සිංහල‬‪ไทย‬‪ລາວ‬‪မြန်မာ‬‪ខ្មែរ‬‪한국어‬‪中文（香港）‬‪日本語‬‪简体中文‬‪繁體中文‬Войти в аккаунтПрежде чем перейти к GoogleМы используем файлы cookie и данные, чтобы:Предоставлять сервисы Google и обеспечивать их работу.Отслеживать сбои и обеспечивать защиту от спама, мошенничества и злоупотреблений.Анализировать вовлеченность аудитории и статистику сайтов, чтобы узнавать, как пользуются нашими сервисами, и улучшать их.Если вы выберете &quot;Принять все&quot;, мы также будем использовать файлы cookie и данные, чтобы:Разрабатывать и улучшать новые сервисы.Показывать рекламу и оценивать ее эффективность.Показывать персонализированный контент (в зависимости от выбранных вами настроек).Показывать персонализированную рекламу (в зависимости от выбранных вами настроек).Если вы выберете &quot;Отклонить все&quot;, мы не будем использовать файлы cookie для этих целей.Неперсонализированные материалы подбираются с учетом таких факторов, как контент, который вы просматриваете в данный момент, ваши действия в текущем сеансе поиска и ваше местоположение. Неперсонализированная реклама подбирается с учетом контента, который вы просматриваете в данный момент, и вашего местоположения. Персонализированные материалы и реклама также могут включать более актуальные результаты, рекомендации и объявления, подобранные с учетом истории ваших действий в текущем браузере, например поисковых запросов в Google. Если это необходимо, мы также используем файлы cookie и данные, чтобы показывать материалы в соответствии с возрастом пользователей.Выберите &quot;Другие варианты&quot;, чтобы получить дополнительную информацию, в том числе об управлении настройками конфиденциальности. Вы также можете в любое время перейти на страницу g.co/privacytools.Отклонить всеПринять всеДругие вариантыКонфиденциальность·Условия использования</value>
      <webElementGuid>e73487f0-4c8e-41dc-bb8e-ec9512be61a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CXQnmb&quot;)</value>
      <webElementGuid>4645e2ba-26bd-4376-990f-bdab8e47243b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='CXQnmb']</value>
      <webElementGuid>a2bd2d24-85e4-44fe-8733-f14076a13260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xe7COe']/div[3]/span/div</value>
      <webElementGuid>7397057e-0802-4d61-b04f-62c8a0eaf06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Тёмная тема: откл.'])[1]/following::div[10]</value>
      <webElementGuid>8f8fd470-9844-4dd4-a41e-077194a09f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Отправить отзыв'])[1]/following::div[14]</value>
      <webElementGuid>fe290d86-9279-48e2-af8a-c8fff7952b53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div</value>
      <webElementGuid>74f86600-bbe3-46d2-baf0-7d30e2bbabde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'CXQnmb' and (text() = 'ru‪Русский‬‪Afrikaans‬‪azərbaycan‬‪bosanski‬‪català‬‪Čeština‬‪Cymraeg‬‪Dansk‬‪Deutsch‬‪eesti‬‪English (United Kingdom)‬‪English (United States)‬‪English‬‪Español (España)‬‪Español (Latinoamérica)‬‪euskara‬‪Filipino‬‪Français (Canada)‬‪Français (France)‬‪Gaeilge‬‪galego‬‪Hrvatski‬‪Indonesia‬‪isiZulu‬‪íslenska‬‪Italiano‬‪Kiswahili‬‪latviešu‬‪lietuvių‬‪magyar‬‪Melayu‬‪Nederlands‬‪norsk‬‪o‘zbek‬‪polski‬‪Português (Brasil)‬‪Português (Portugal)‬‪română‬‪shqip‬‪Slovenčina‬‪slovenščina‬‪srpski (latinica)‬‪Suomi‬‪Svenska‬‪Tiếng Việt‬‪Türkçe‬‪Ελληνικά‬‪беларуская‬‪български‬‪кыргызча‬‪македонски‬‪монгол‬‪српски (ћирилица)‬‪Українська‬‪ქართული‬‪қазақ тілі‬‪հայերեն‬‫עברית‬‫اردو‬‫العربية‬‫فارسی‬‪አማርኛ‬‪नेपाली‬‪मराठी‬‪हिन्दी‬‪বাংলা‬‪ਪੰਜਾਬੀ‬‪ગુજરાતી‬‪தமிழ்‬‪తెలుగు‬‪ಕನ್ನಡ‬‪മലയാളം‬‪සිංහල‬‪ไทย‬‪ລາວ‬‪မြန်မာ‬‪ខ្មែរ‬‪한국어‬‪中文（香港）‬‪日本語‬‪简体中文‬‪繁體中文‬Войти в аккаунтПрежде чем перейти к GoogleМы используем файлы cookie и данные, чтобы:Предоставлять сервисы Google и обеспечивать их работу.Отслеживать сбои и обеспечивать защиту от спама, мошенничества и злоупотреблений.Анализировать вовлеченность аудитории и статистику сайтов, чтобы узнавать, как пользуются нашими сервисами, и улучшать их.Если вы выберете &quot;Принять все&quot;, мы также будем использовать файлы cookie и данные, чтобы:Разрабатывать и улучшать новые сервисы.Показывать рекламу и оценивать ее эффективность.Показывать персонализированный контент (в зависимости от выбранных вами настроек).Показывать персонализированную рекламу (в зависимости от выбранных вами настроек).Если вы выберете &quot;Отклонить все&quot;, мы не будем использовать файлы cookie для этих целей.Неперсонализированные материалы подбираются с учетом таких факторов, как контент, который вы просматриваете в данный момент, ваши действия в текущем сеансе поиска и ваше местоположение. Неперсонализированная реклама подбирается с учетом контента, который вы просматриваете в данный момент, и вашего местоположения. Персонализированные материалы и реклама также могут включать более актуальные результаты, рекомендации и объявления, подобранные с учетом истории ваших действий в текущем браузере, например поисковых запросов в Google. Если это необходимо, мы также используем файлы cookie и данные, чтобы показывать материалы в соответствии с возрастом пользователей.Выберите &quot;Другие варианты&quot;, чтобы получить дополнительную информацию, в том числе об управлении настройками конфиденциальности. Вы также можете в любое время перейти на страницу g.co/privacytools.Отклонить всеПринять всеДругие вариантыКонфиденциальность·Условия использования' or . = 'ru‪Русский‬‪Afrikaans‬‪azərbaycan‬‪bosanski‬‪català‬‪Čeština‬‪Cymraeg‬‪Dansk‬‪Deutsch‬‪eesti‬‪English (United Kingdom)‬‪English (United States)‬‪English‬‪Español (España)‬‪Español (Latinoamérica)‬‪euskara‬‪Filipino‬‪Français (Canada)‬‪Français (France)‬‪Gaeilge‬‪galego‬‪Hrvatski‬‪Indonesia‬‪isiZulu‬‪íslenska‬‪Italiano‬‪Kiswahili‬‪latviešu‬‪lietuvių‬‪magyar‬‪Melayu‬‪Nederlands‬‪norsk‬‪o‘zbek‬‪polski‬‪Português (Brasil)‬‪Português (Portugal)‬‪română‬‪shqip‬‪Slovenčina‬‪slovenščina‬‪srpski (latinica)‬‪Suomi‬‪Svenska‬‪Tiếng Việt‬‪Türkçe‬‪Ελληνικά‬‪беларуская‬‪български‬‪кыргызча‬‪македонски‬‪монгол‬‪српски (ћирилица)‬‪Українська‬‪ქართული‬‪қазақ тілі‬‪հայերեն‬‫עברית‬‫اردو‬‫العربية‬‫فارسی‬‪አማርኛ‬‪नेपाली‬‪मराठी‬‪हिन्दी‬‪বাংলা‬‪ਪੰਜਾਬੀ‬‪ગુજરાતી‬‪தமிழ்‬‪తెలుగు‬‪ಕನ್ನಡ‬‪മലയാളം‬‪සිංහල‬‪ไทย‬‪ລາວ‬‪မြန်မာ‬‪ខ្មែរ‬‪한국어‬‪中文（香港）‬‪日本語‬‪简体中文‬‪繁體中文‬Войти в аккаунтПрежде чем перейти к GoogleМы используем файлы cookie и данные, чтобы:Предоставлять сервисы Google и обеспечивать их работу.Отслеживать сбои и обеспечивать защиту от спама, мошенничества и злоупотреблений.Анализировать вовлеченность аудитории и статистику сайтов, чтобы узнавать, как пользуются нашими сервисами, и улучшать их.Если вы выберете &quot;Принять все&quot;, мы также будем использовать файлы cookie и данные, чтобы:Разрабатывать и улучшать новые сервисы.Показывать рекламу и оценивать ее эффективность.Показывать персонализированный контент (в зависимости от выбранных вами настроек).Показывать персонализированную рекламу (в зависимости от выбранных вами настроек).Если вы выберете &quot;Отклонить все&quot;, мы не будем использовать файлы cookie для этих целей.Неперсонализированные материалы подбираются с учетом таких факторов, как контент, который вы просматриваете в данный момент, ваши действия в текущем сеансе поиска и ваше местоположение. Неперсонализированная реклама подбирается с учетом контента, который вы просматриваете в данный момент, и вашего местоположения. Персонализированные материалы и реклама также могут включать более актуальные результаты, рекомендации и объявления, подобранные с учетом истории ваших действий в текущем браузере, например поисковых запросов в Google. Если это необходимо, мы также используем файлы cookie и данные, чтобы показывать материалы в соответствии с возрастом пользователей.Выберите &quot;Другие варианты&quot;, чтобы получить дополнительную информацию, в том числе об управлении настройками конфиденциальности. Вы также можете в любое время перейти на страницу g.co/privacytools.Отклонить всеПринять всеДругие вариантыКонфиденциальность·Условия использования')]</value>
      <webElementGuid>7af38cad-d834-44c1-a864-d81b7fde807b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
